### ISSUE TITLE
Sync error with Jellyfin and Emby

### ISSUE THREAD

**Issue by edrock200** [mregni/EmbyStat#1266]
# Bug report

**Describe the bug**
A fresh install of Embystats Beta 20, Beta 19 or Beta 18 will not sync with Jellyfin or Emby. The users, plugins, and library names seem to sync properly, but the libraries always error out no matter what I try. This is using the docker containers.

**To Reproduce**

Install Embystats beta 18, 19 or 20 docker version, point to jellyfin or emby, attempt media sync.

**Expected behavior**
Media syncs

**Screenshots**
See log below, but this error seems to be the start of a domino effect:
[ERROR] Error while running job LiteDB.LiteException: Index key must be less than 255 bytes.

**System (please complete the following information):**

- OS: Host is ubuntu 18.04
- Browser Chrome
- Version Beta 20

**Additional context**
```2020-07-28 08:21:44.5590 [INFO] MEDIASYNC-JOB	Starting job 
2020-07-28 08:21:44.7168 [INFO] MEDIASYNC-JOB	First delete all existing media and root media libraries from database so we have a clean start. 
2020-07-28 08:21:44.7168 [INFO] MEDIASYNC-JOB	Asking MediaServer for all root folders 
2020-07-28 08:21:44.8680 [INFO] MEDIASYNC-JOB	Found 38 root items, getting ready for processing 
2020-07-28 08:21:44.8680 [INFO] MEDIASYNC-JOB	Lets start processing movies 
2020-07-28 08:21:45.0626 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-07-28 08:21:45.1425 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-07-28 08:21:48.2916 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=removed
2020-07-28 08:21:49.2635 [WARN] Failed to process the job 'removed': an exception occurred. Retry attempt 2 of 2 will be performed in 00:01:08. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-07-28 08:21:53.1402 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=removed
2020-07-28 08:21:58.1405 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=removed
2020-07-28 08:22:03.1388 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=removed 
2020-07-28 08:22:04.3153 [INFO] SMALLEMBYSYNC-JOB	Starting job 
2020-07-28 08:22:04.5035 [INFO] SMALLEMBYSYNC-JOB	Server info downloaded 
2020-07-28 08:22:04.6465 [INFO] SMALLEMBYSYNC-JOB	Server plugins downloaded 
2020-07-28 08:22:05.2483 [INFO] SMALLEMBYSYNC-JOB	Server users downloaded 
2020-07-28 08:22:05.3558 [ERROR] Error while running job LiteDB.LiteException: Index key must be less than 255 bytes.
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.SharedEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 entities)
   at EmbyStat.Repositories.MediaServerRepository.<>c__DisplayClass17_0.<UpsertDevices>b__0()
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query)
   at EmbyStat.Repositories.MediaServerRepository.UpsertDevices(IEnumerable`1 devices)
   at EmbyStat.Services.MediaServerService.GetAndProcessDevices()
   at EmbyStat.Jobs.Jobs.Sync.SmallSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-07-28 08:22:05.5705 [ERROR] SMALLEMBYSYNC-JOB	Job failed, check logs for more info. ```

**Comment by mregni** [comment]
It is possible that this is already fixed in the code I have locally. We need to retest this when beta.21 is released. 
I'm doing my best to finish the release this week but can't promise anything.

**Comment by edrock200** [comment]
Oh I gotcha. Thanks! Much appreciated.

**Comment by Protektor-Desura** [comment]
Beta 22, does not seem to fix this error. I am still not able to get a movie sync with Jellyfin.

I also am not able to download logs because I get "Unhandled backend exception" error when trying to download them.

7:00:01 PM 08/07/2020 - MEDIA-SYNC - First delete all existing media and root media libraries from database so we have a clean start.
7:00:01 PM 08/07/2020 - MEDIA-SYNC - Asking MediaServer for all root folders
7:00:01 PM 08/07/2020 - MEDIA-SYNC - Found 9 root items, getting ready for processing
7:00:01 PM 08/07/2020 - MEDIA-SYNC - Lets start processing movies
7:00:02 PM 08/07/2020 - MEDIA-SYNC - 0 movies found in parent with id f137a2dd21bbc1b99aa5c0f6bf02a805. Propably means something is wrong with the HTTP call.
7:00:02 PM 08/07/2020 - MEDIA-SYNC - Calculating movie statistics
7:00:07 PM 08/07/2020 - MEDIA-SYNC - Calculation 1/2 done

Yes this was a clean install and yes I gave it a user to login to Jellyfin, but I don't think it asked me for a password for that account when setting it up.

**Comment by mregni** [comment]
@Protektor-Desura, what OS is running EmbyStat on? Because you can also navigate to the /Logs folder to check for them. It's normal that EmbyStat not asking for a Jellyfin password because you supplied EmbyStat with an API token.

Your problem does seem like a different one than initially posted because your instance is able to fetch the movie count.

**Comment by Protektor-Desura** [comment]
It doesn't fetch the movie count but rather the number of libraries. I have 9 libraries because Jellyfin supports way more file types than Emby now. I have:

Audiobooks
Books
Collections
Comic Books
Movies
Music
Music Videos
Recordings (Live TV recorded)
TV Shows

It doesn't appear to download any movies or TV shows from Jellyfin.

I am running EmbyStat on Ubuntu 20.04 and inside docker. Jellyfin also runs in docker as well. I wonder if there is a problem with the size of my libraries because they are quiet large. Everything totals to over 30+TB of data, most of it in HEVC format. So I have 4,583 movies and 1,695 TV shows with a total of 51,073 episodes.

**Comment by mregni** [comment]
That a heavy collection. But getting te total movie count should not be a problem. 
AS far as I can see EmbyStat is searching in your library with id f137a2dd21bbc1b99aa5c0f6bf02a805 for movies (can you just verify that's the correct one and there is no bug in the lib selector in EmbyStat?)

For some reason, Jellyfin is responding with 0 movies. I'll spin up my Jellyfin instance to check if I have the same problem.

**Comment by john-sp** [comment]
I have the same problem with the exact same ID, the ID is the poster of the Movies Library

**Comment by mregni** [comment]
@john-sp, you are saing that f137a2dd21bbc1b99aa5c0f6bf02a805 is a poster id? Because that would couse for errors indeed.

**Comment by mregni** [comment]
#1155 seems to be the same problem

**Comment by Protektor-Desura** [comment]
Embystat has never pulled any movies or TV shows for me from Jellyfin.

**Comment by mregni** [comment]
I got it working on my Jellyfin test server. Is there a way you can run the following docker container?
`docker run -v <local-data-path>:C:\app\data -p <port>:6555 -e EMBYSTAT_LOGLEVEL=1 uping/embystat:nightly`

This will enable some new debug logging that is not yet in the beta release and also log file download is fixed in nightly. Let's hope I can see why EmbyStat is not syncing Jellyfin data on your servers.

**Comment by edrock200** [comment]
> @Protektor-Desura, what OS is running EmbyStat on? Because you can also navigate to the /Logs folder to check for them. It's normal that EmbyStat not asking for a Jellyfin password because you supplied EmbyStat with an API token.
> 
> Your problem does seem like a different one than initially posted because your instance is able to fetch the movie count.

I'm the original poster, I believe you were replying to someone else that chimed in on this thread. I don't know if their problem is the same or different from mine. I'll try the latest nightly and report back. Thank you!

**Comment by mregni** [comment]
@edrock200, I saw someone else posting in your thread indeed. But since he also has a problem with fetching the movie count API call I'm presuming it's the same problem. Let me know when you had the time to test the nightly, hopefully the debug info will tell me more about the problem.

**Comment by mregni** [comment]
#1155 and #1218 both have the same issue probably

**Comment by Protektor-Desura** [comment]
I tried it but it keeps saying it is failing the server ping but the logs say it is passing.
2020-08-12 11:51:45.8027 [DEBUG] BASE-HTTP-CLIENT	External call: [POST]http://192.168.1.10:8096//System/Ping 
2020-08-12 11:51:45.8156 [DEBUG] BASE-HTTP-CLIENT	Ping returned: Jellyfin Server 
I called my server "Jellyfin". But the log files are working now and I can download them.

**Comment by Happy2Play** [comment]
This is interesting as I have a Test stable and beta Emby servers and ,22 will run on fine but my primary Emby Beta server throws this error.

2020-08-12 15:07:58.2574 [WARN] MEDIA-SYNC	Movie error: Object reference not set to an instance of an object. 
2020-08-12 15:07:58.2574 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Common.Extensions.BaseItemDtoExtension.<>c__2`1.<MapPeople>b__2_0(BaseItemPerson y)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at EmbyStat.Common.Extensions.BaseItemDtoExtension.MapPeople[T](BaseItemDto dto, T extra)
   at EmbyStat.Clients.Base.Converters.MovieConverter.ConvertToMovie(BaseItemDto dto, String collectionId)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-08-12 15:07:58.2797 [WARN] MEDIA-SYNC	Job failed, check logs for more info. 
2020-08-12 15:07:58.3616 [ERROR] Failed to process the job '4dc1e15c-bb29-4097-8d81-c2e02034a3ff': an exception occurred. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Common.Extensions.BaseItemDtoExtension.<>c__2`1.<MapPeople>b__2_0(BaseItemPerson y)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at EmbyStat.Common.Extensions.BaseItemDtoExtension.MapPeople[T](BaseItemDto dto, T extra)
   at EmbyStat.Clients.Base.Converters.MovieConverter.ConvertToMovie(BaseItemDto dto, String collectionId)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by mregni** [comment]
@Happy2Play, I moved your issue to a seperate issue because it seems to be another sync bug

@Protektor-Desura, can you provide me the full log file so I can see what flow EmbyStat is taking up until the ping?

**Comment by gerben838665** [comment]
I have the same problem as @Protektor-Desura where Embystat gives me the following error when doing a media synchronization:
MEDIA-SYNC - 0 movies found in parent with id f137a2dd21bbc1b99aa5c0f6bf02a805. Propably means something is wrong with the HTTP call.

I'm running embystat through unraid and got this error in the linuxserver/embystat docker and the above posted uping/embystat:nightly docker.

i also looked into the Jellyfin logs and found embystat sending the following 2 get requests during media synchronization:
http://[serverdomain]/Items?ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&StartIndex=0&recursive=True&IncludeItemTypes=Movie
http://[serverdomain]/Items?UserId=fa89fb6c-f3b7-4cc5-bc17-9522e3b94246&SeriesStatuses=&fields=&Filters=&ImageTypes=&AirDays=&EnableImageTypes=&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&StartIndex=0&Limit=1&recursive=True&IncludeItemTypes=Movie%2cBoxSet

Both get requests gave the following error in the jellyfin logs:
System.NullReferenceException: Object reference not set to an instance of an object.

After some quick testing with get requests i think i found the problem.
embystat is not using a userid in the first get request and a non existing userid in it's second get request
"UserId=fa89fb6c-f3b7-4cc5-bc17-9522e3b94246"
In a quick search this userid seems to be hardcoded into the following two files:
Tests.Unit/Clients/BaseHttpClientTests.cs
Tests.Unit/Extensions/RestRequestExtensionTests.cs

When i change the userid to the userid of my jellyfin admin account the get requests seems to work.

I also noticed that embystat already saved the userid of my jellyfin admin account in the usersettings.json file.
under MediaServer, UserID.

**Comment by Protektor-Desura** [comment]
Still getting the same error on the lastest update that I got today.
0.2.1-dev.1279
2:33:48 PM 08/13/2020 - MEDIA-SYNC - 0 movies found in parent with id f137a2dd21bbc1b99aa5c0f6bf02a805. Propably means something is wrong with the HTTP call.
Also you have a typo with word "probably".

I will say I am no longer having the ping error though.

**Comment by mregni** [comment]
Thanks for making me aware that you guys are all using my user id. I found the hardcoded id in the RestRequestExtention.cs file. Made it dynamic now, so I'm going to create another nightly so you can test it. 

Let's hope this fixes the problem! :D

**Comment by mregni** [comment]
@edrock200, @Protektor-Desura, @gerben838665, new nightly is created, this should make the user-id dynamic. If someone can test this for me we hopefully can close this issue :)

**Comment by gerben838665** [comment]
@mregni, Just tested the new nightly. Embystat seems to sync without any problems for me now.
Thanks for implementing the fix.

**Comment by Protektor-Desura** [comment]
I just tested the new nightly and it got much farther but didn't finish. It errored out for me. Ping is also still failing for me.
0.2.1-dev.1283


4:49:32 AM 08/14/2020 - MEDIA-SYNC - Processed 4417 / 4417 movies
4:49:36 AM 08/14/2020 - MEDIA-SYNC - Found 372 box sets in Movies library
5:01:03 AM 08/14/2020 - MEDIA-SYNC - Movie error: Object reference not set to an instance of an object.
5:01:04 AM 08/14/2020 - MEDIA-SYNC - Job failed, check logs for more info.
5:01:43 AM 08/14/2020 - MEDIA-SYNC - Starting job
5:01:43 AM 08/14/2020 - MEDIA-SYNC - First delete all existing media and root media libraries from database so we have a clean start.
5:01:43 AM 08/14/2020 - MEDIA-SYNC - Asking MediaServer for all root folders
5:01:43 AM 08/14/2020 - MEDIA-SYNC - Found 9 root items, getting ready for processing
5:01:43 AM 08/14/2020 - MEDIA-SYNC - Lets start processing movies
5:03:24 AM 08/14/2020 - MEDIA-SYNC - 0 movies found in parent with id f137a2dd21bbc1b99aa5c0f6bf02a805. Probably means something is wrong with the HTTP call.
5:03:24 AM 08/14/2020 - MEDIA-SYNC - Calculating movie statistics
5:03:26 AM 08/14/2020 - MEDIA-SYNC - Calculation 1/2 done
5:03:27 AM 08/14/2020 - MEDIA-SYNC - Calculation 2/2 done
5:03:27 AM 08/14/2020 - MEDIA-SYNC - Job finished after 2 minutes.


2020-08-14 05:01:03.5665 [WARN] MEDIA-SYNC	Movie error: Object reference not set to an instance of an object. 
2020-08-14 05:01:03.5665 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovies(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-08-14 05:01:04.7066 [WARN] MEDIA-SYNC	Job failed, check logs for more info. 
2020-08-14 05:01:07.1182 [WARN] Failed to process the job 'f1260b4a-66eb-4114-9077-b1f355db0c3f': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:28. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovies(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-08-14 05:01:07.4837 [DEBUG] SERVER-API	Pinging server on http://192.168.1.10:8096 
2020-08-14 05:01:07.4837 [DEBUG] BASE-HTTP-CLIENT	External call: [POST]http://192.168.1.10:8096//System/Ping 
2020-08-14 05:01:07.4837 [DEBUG] BASE-HTTP-CLIENT	Ping returned: Jellyfin Server 
2020-08-14 05:01:08.1597 [DEBUG] BASE-HTTP-CLIENT	Call failed => StatusCode:0, Content: 
2020-08-14 05:01:09.8275 [DEBUG] BASE-HTTP-CLIENT	External call: [GET]http://192.168.1.10:8096/persons/Anthony Daniels 
2020-08-14 05:01:10.0729 [DEBUG] SERVER-API	Pinging server on http://192.168.1.10:8096 
2020-08-14 05:01:10.0729 [DEBUG] BASE-HTTP-CLIENT	External call: [POST]http://192.168.1.10:8096//System/Ping 
2020-08-14 05:01:10.6000 [DEBUG] BASE-HTTP-CLIENT	Ping returned: Jellyfin Server 
2020-08-14 05:02:49.9027 [DEBUG] BASE-HTTP-CLIENT	External call: [GET]http://192.168.1.10:8096/persons/Robert Downey Jr. 
2020-08-14 05:03:25.0765 [DEBUG] BASE-HTTP-CLIENT	Call failed => StatusCode:0, Content: 
2020-08-14 05:03:25.0765 [WARN] MEDIA-SYNC	0 movies found in parent with id f137a2dd21bbc1b99aa5c0f6bf02a805. Probably means something is wrong with the HTTP call. 
2020-08-14 05:03:25.0808 [INFO] MEDIA-SYNC	Calculating movie statistics 
2020-08-14 05:03:26.6062 [INFO] MEDIA-SYNC	Calculation 1/2 done 
2020-08-14 05:03:27.5738 [INFO] MEDIA-SYNC	Calculation 2/2 done 
2020-08-14 05:03:27.9281 [INFO] MEDIA-SYNC	Job finished after 2 minutes. 
2020-08-14 05:04:29.9038 [DEBUG] BASE-HTTP-CLIENT	Call failed => StatusCode:0, Content: 
2020-08-14 05:04:30.1987 [DEBUG] BASE-HTTP-CLIENT	External call: [GET]http://192.168.1.10:8096/persons/Desmond Llewelyn 
2020-08-14 05:05:14.6604 [DEBUG] SERVER-API	Pinging server on http://192.168.1.10:8096 
2020-08-14 05:05:14.6604 [DEBUG] BASE-HTTP-CLIENT	External call: [POST]http://192.168.1.10:8096//System/Ping 
2020-08-14 05:05:14.6604 [DEBUG] BASE-HTTP-CLIENT	Ping returned: Jellyfin Server

**Comment by Protektor-Desura** [comment]
Ping still fails for me so nothing works.
0.2.1-dev.1285

2020-08-14 12:40:16.7193 [DEBUG] SERVER-API	Pinging server on http://192.168.1.10:8096 
2020-08-14 12:40:16.7193 [DEBUG] BASE-HTTP-CLIENT	External call: [POST]http://192.168.1.10:8096//System/Ping 
2020-08-14 12:40:16.7232 [DEBUG] BASE-HTTP-CLIENT	Ping returned: Jellyfin Server 
2020-08-14 12:41:17.5576 [INFO] MEDIA-SYNC	Starting job 
2020-08-14 12:41:18.3829 [DEBUG] BASE-HTTP-CLIENT	External call: [POST]http://192.168.1.10:8096//System/Ping 
2020-08-14 12:41:18.3884 [DEBUG] BASE-HTTP-CLIENT	Ping returned: Jellyfin Server 
2020-08-14 12:41:18.3884 [WARN] MEDIA-SYNC	Halting task because we can't contact the server on http://192.168.1.10:8096, please check the connection and try again. 
2020-08-14 12:41:18.6602 [INFO] MEDIA-SYNC	Job finished after 1 minute. 

"Jellyfin Server" is just what I happen to name my server inside Jellyfin.

**Comment by mregni** [comment]
@Protektor-Desura, did you remove the baseurl while running the wizard by accident (or later in the usersettings.json file)? Normally Jellyfin servers need a /jellyfin baseurl. As I see from the debug urls there are two / instead of just one. It should be /jellyfin/System/Ping normally.


"Jellyfin Server" is the reply a Jellyfin server gives when you call the ping API.

**Comment by Protektor-Desura** [comment]
My system does not require or use a baseurl. In fact that hasn't been used by Jellyfin for awhile. You can turn it on if you need it but most should not need it. It adds further complications for the clients as well.

**Comment by mregni** [comment]
Ha by default it's still there (was on my test Jellyfin server anyway). Good to know that! Then you should open your usersettings.json file and remove the "/" from the "ServerBaseUrl" property. I will create a fix that clears the baseurl when it's just "/".

Can you test it again when you were able to clear the baseurl in the json file (also restart your EmbyStat server after the change)

**Comment by Protektor-Desura** [comment]
My usersettings.json appears to already have it removed.

  "MediaServer": {
    "ServerName": "",
    "ApiKey": "xxxxxxx",
    "ServerAddress": "192.168.1.10",
    "ServerPort": 8096,
    "AuthorizationScheme": "MediaBrowser",
    "ServerProtocol": 1,
    "ServerType": 0,
    "UserId": "6d772cef81c34038b604fde808382347",
    "ServerBaseUrl": null,
    "ServerId": "861dbb0e00f048b9b8085beb6615bb76"

I thought maybe because my ServerName was blank that it was causing the ping failure so I set it to "Jellyfin" and I am still getting ping failure.

**Comment by Protektor-Desura** [comment]
Still getting the failed ping string so it won't even try to connect now because it tests the ping before trying to connect and get the list of media.

**Comment by mregni** [comment]
@edrock200, can you check if your problem is resolved at the moment in the nightly build?

@Protektor-Desura, going to create a new issue for your problem because it is a different one than the original problem.

**Comment by edrock200** [comment]
Hey, thanks for getting back to me on this. I installed the latest last night and it does sync now. I have the white screen issue now on movies/general, and no "Shows" sub tab, but those are separate issues so I'm closing this one. Thanks!
