### ISSUE TITLE
Actor, Director, Writer stats issues

### ISSUE THREAD

**Issue by diedrichg** [mregni/EmbyStat#826]
# Bug report

**Describe the bug**
**Movies Page:**

- [x] The Actor Stats section does not have a header title
- [x] Under the Actor Stats section, the grey-on-grey text is hard to read - suggest white.
- [x] Under the Actor Stats section - at first Bruce Willis didn't have a birthdate, after a while he did. I'm assuming the database is still being populated?
- [x] None of the actors in the Actor Stats section have a movie or shows count, they all read 0 / 0

**System (please complete the following information):**
- OS: Windows
- Version: v0.2.0-beta.4

**Comment by mregni** [comment]
Going to mark this as a bug because of the birthday issue. If it's displayed for an actor it should be displayed everywhere for that actor.

I fixed the movie and show count, that should come in the next beta release soon.

(updated your comment to have a checklist)

**Comment by mregni** [comment]
Fixed 3/4 issues. @diedrichg can you check if you have still the issue with missing birth dates in the list?

**Comment by diedrichg** [comment]
Some are not showing birthdates even though they are available in Emby. I can't find the attachment button in the mobile view to upload screenshots

**Comment by diedrichg** [comment]
I did a complete FRESH install - deleting the database and everything. I'm still not getting the birth dates for a couple of the actors/directors.

Log attached.
[2019-08-07.log](https://github.com/mregni/EmbyStat/files/3478877/2019-08-07.log)

Alec Baldwin is at the bottom
![Screenshot_2019-08-07-04 EmbyStat](https://user-images.githubusercontent.com/9559987/62657312-33ccab80-b934-11e9-828f-f30e51ddc4d0.png)

His birth date is available in Emby
![Screenshot_2019-08-07 Emby](https://user-images.githubusercontent.com/9559987/62657440-7ee6be80-b934-11e9-9747-f311994eeef2.png)

Same for Frank Oz
![Screenshot_2019-08-07-03 EmbyStat](https://user-images.githubusercontent.com/9559987/62657357-53fc6a80-b934-11e9-896b-07e34b28e684.png)

![Screenshot_2019-08-07-02 Emby](https://user-images.githubusercontent.com/9559987/62657365-58288800-b934-11e9-955a-fb862c6904d5.png)

**Comment by diedrichg** [comment]
On TV Shows I'm getting only two birth dates out of the whole list.

**Comment by Happy2Play** [comment]
Looks like if the "Brith Year" field is not populated this causes issues displaying "Birthdate".  I added Birth Year to items not displaying Biithdate and now they are displaying Birthdate.

@diedrichg are all the actors that are missing Birthdate, missing Birth Year in their metadata?

**Comment by mregni** [comment]
This is the code where I convert the people into embystat dto's 
![image](https://user-images.githubusercontent.com/22617019/62682512-a5503c80-b9bc-11e9-860e-ea2b1902f876.png)
There is no birthdate on the Emby BaseItemDto but it looked correct to me to use the PremieredDate to get the birthday. Maybe I'm using the wrong property on the BaseItemDto. I'll debug some more!

**Comment by diedrichg** [comment]
> 
> 
> Looks like if the "Brith Year" field is not populated this causes issues displaying "Birthdate". I added Birth Year to items not displaying Biithdate and now they are displaying Birthdate.
> 
> @diedrichg are all the actors that are missing Birthdate, missing Birth Year in their metadata?

A day later and now Baldwin and Oz have their birthdates populated in EmbyStat. There is one actor whose birthday is not being displayed and @Happy2Play is correct, their metadata does not have their birth year populated. I just now entered the birth year, performed a sync, and now their birthdate is populated in EmbyStat.

**Comment by mregni** [comment]
I'm going to force the birthdate in the http call for people. But for some reason sometimes it just doesn't get returned it seems. Very strange

**Comment by mregni** [comment]
I merged a new fix, let's hope the last issue will be fixed now. I'll leave the issue open until tested on beta

**Comment by mregni** [comment]
Seems like it's fixed. If not, feel free too reopen or create a new issue.
